apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: us8plu8p4-python 
  janus-idp.io/tekton: us8plu8p4-python
  backstage.io/kubernetes-id: us8plu8p4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: us8plu8p4-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml