apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: us8plu8p4-python
  janus-idp.io/tekton: us8plu8p4-python
  backstage.io/kubernetes-id: us8plu8p4-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: us8plu8p4-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
