apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: us8plu8p4-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: us8plu8p4-python 
  name: us8plu8p4-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: us8plu8p4-python 
